include ../../Makefile.conf

build: hello.elf

hello.elf: *.cpp
	$(BIN_PATH)/clang++ -march=rv32imc -mabi=ilp32 -fno-rtti --stdlib=$(STDLIB) -nostartfiles -lsemihost -ltest_support -lcrt1_sim_test -L $(TEST_LIB_BASE_DIR)/rv32imc-zicsr-zifencei_ilp32_no-rtti/lib -g -T ../../ldscripts/esp32c3.ld -o hello.elf $^

run: hello.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel $<

debug: hello.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel -g 1234 $<

clean:
	rm -f *.elf

.PHONY: clean run debug
