include ../../Makefile.conf

build: hello.elf

# TODO: LLVM-250. Have to use '--rtlib=libgcc' until 'libnunwind' is supported.
hello.elf: *.cpp
	$(BIN_PATH)/clang++ -march=rv32imc -mabi=ilp32 -fno-rtti --rtlib=libgcc --unwindlib=none -nostartfiles -lcrt1-sim -lsemihost -lpthread_stubs -g -T ../../ldscripts/esp32c3.ld -o hello.elf $^

run: hello.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel $<

debug: hello.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel -g 1234 $<

clean:
	rm -f *.elf

.PHONY: clean run debug
