include ../../Makefile.conf

build: hello.elf hello-exn.elf

hello.elf: hello.cpp
	$(BIN_PATH)/clang++ -march=rv32imc -mabi=ilp32 -fno-exceptions -fno-rtti $(STDLIB) -nostartfiles -lsemihost -ltest_support -lcrt1_sim_test -L $(TEST_LIB_BASE_DIR)/rv32imc-zicsr-zifencei_ilp32_no-rtti/lib -g -T ../../ldscripts/esp32c3.ld -o hello.elf $^

hello-exn.elf: hello-exn.cpp
	$(BIN_PATH)/clang++ -march=rv32imc -mabi=ilp32 -fno-rtti $(STDLIB) -nostartfiles -lsemihost -ltest_support -lcrt1_sim_test -L $(TEST_LIB_BASE_DIR)/rv32imc-zicsr-zifencei_ilp32_no-rtti/lib -g -T ../../ldscripts/esp32c3.ld -o hello-exn.elf $^

run: hello.elf hello-exn.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel hello.elf
	qemu-system-riscv32 -nographic -machine esp32c3 --semihosting -kernel hello-exn.elf  2>&1 | grep "caught"

clean:
	rm -f *.elf

.PHONY: clean run
